name: OKE helm demo
run-name: ${{ github.actor }} is testing out GitHub Actions
on: [push]
jobs:
  setup-helm:
    runs-on: ubuntu-latest
    name: Setup kubeconfig & helm
    env:
      OCI_CLI_USER: ${{ secrets.OCI_CLI_USER }}
      OCI_CLI_TENANCY: ${{ secrets.OCI_CLI_TENANCY }}
      OCI_CLI_FINGERPRINT: ${{ secrets.OCI_CLI_FINGERPRINT }}
      OCI_CLI_KEY_CONTENT: ${{ secrets.OCI_CLI_KEY_CONTENT }}
      OCI_CLI_REGION: ${{ secrets.OCI_CLI_REGION }}

    steps:
      - name: setup kubeconfig
        uses: oracle-actions/configure-kubectl-oke@v1.5.0
        id: test-configure-kubectl-oke-action
        with:
          cluster: ${{ secrets.OKE_CLUSTER_OCID }}
      
      - uses: azure/setup-helm@v4.2.0
        with:
          version: 'latest'
        id: install
      
      - name: Run helm
        run: helm list -A